import { useEffect, useState } from 'react'
import { Link, NavLink, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import { productsApi } from './api'
import type { Product, ProductPage } from './types'

const imageSource = (source?: string) => source || 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80'
const money = new Intl.NumberFormat('es-AR', { style: 'currency', currency: 'ARS', maximumFractionDigits: 0 })

function Brand() { return <Link to="/" className="brand" aria-label="Horizonte, página principal"><span className="brand-mark">H</span><span><strong>Horizonte</strong><small>estancias que inspiran</small></span></Link> }
function Header() { return <header className="site-header"><Brand /><nav><NavLink to="/">Explorar</NavLink><NavLink to="/administracion">Administración</NavLink></nav><div className="header-actions"><button className="ghost" type="button">Crear cuenta</button><button className="outline" type="button">Iniciar sesión</button></div></header> }
function Footer() { return <footer><Brand /><span>© {new Date().getFullYear()} Horizonte. Hecho para viajar despacio.</span></footer> }
function Layout({ children }: {children: React.ReactNode}) { return <div className="app-shell"><Header /><main>{children}</main><Footer /></div> }

function ProductCard({ product }: {product: Product}) { return <Link className="product-card" to={`/productos/${product.id}`}><img src={imageSource(product.images[0])} alt={`Vista de ${product.name}`} /><div className="card-content"><div className="eyebrow">{product.category} · {product.city}</div><h3>{product.name}</h3><p>{product.description}</p><strong>{money.format(product.price)} <small>/ noche</small></strong></div></Link> }

function Home() {
  const [products, setProducts] = useState<Product[]>([]); const [loading, setLoading] = useState(true)
  useEffect(() => { productsApi.random().then(setProducts).finally(() => setLoading(false)) }, [])
  const categories = ['Cabañas', 'Casas', 'Hoteles', 'Estancias']
  return <Layout><section className="hero"><div><p className="kicker">RESERVAS CON ALMA</p><h1>Encontrá un lugar que se sienta como tuyo.</h1><p className="hero-copy">Estancias singulares para descansar, descubrir y volver a conectar.</p><a href="#recomendadas" className="primary">Explorar alojamientos <span>→</span></a></div><div className="hero-card"><span>◆</span><b>11 destinos</b><small>seleccionados con cuidado</small></div></section><section className="category-section"><div className="section-heading"><p className="kicker">ELEGÍ TU RITMO</p><h2>¿Cómo querés viajar?</h2></div><div className="categories">{categories.map((category, index) => <div className={`category category-${index}`} key={category}><span>{['⌂','◌','⌁','✦'][index]}</span><b>{category}</b><small>Descubrir estadías</small></div>)}</div></section><section id="recomendadas" className="recommendations"><div className="section-heading spread"><div><p className="kicker">SELECCIÓN DEL DÍA</p><h2>Estadías para inspirarte</h2></div><span className="result-count">Hasta 10 recomendaciones aleatorias</span></div>{loading ? <p className="loading">Buscando lugares especiales…</p> : <div className="product-grid">{products.map(product => <ProductCard key={product.id} product={product} />)}</div>}</section></Layout>
}

function Detail() {
  const { id } = useParams(); const navigate = useNavigate(); const [product, setProduct] = useState<Product | null>(null); const [gallery, setGallery] = useState(false)
  useEffect(() => { if (id) productsApi.get(id).then(setProduct) }, [id])
  if (!product) return <Layout><p className="loading">Cargando alojamiento…</p></Layout>
  const images = product.images.slice(0, 5)
  return <Layout><section className="detail-title"><div><p className="kicker">{product.category} · {product.city}</p><h1>{product.name}</h1></div><button onClick={() => navigate(-1)} className="back" type="button">← Volver</button></section><section className="detail-content"><div className="gallery"><img className="gallery-main" src={imageSource(images[0])} alt={`Vista principal de ${product.name}`} /><div className="gallery-side">{images.slice(1, 5).map((image, index) => <img src={imageSource(image)} alt={`Vista ${index + 2} de ${product.name}`} key={image} />)}</div><button onClick={() => setGallery(true)} className="view-more" type="button">Ver más fotos ↗</button></div><article className="description"><p className="kicker">SOBRE LA ESTADÍA</p><h2>Un lugar para bajar el ritmo.</h2><p>{product.description}</p><div className="booking-box"><span>Desde</span><strong>{money.format(product.price)} <small>/ noche</small></strong><button className="primary" type="button">Consultar disponibilidad</button></div></article></section>{gallery && <div className="lightbox" role="dialog" aria-modal="true"><button onClick={() => setGallery(false)} className="close" type="button">×</button><div>{product.images.map((image, index) => <img src={imageSource(image)} alt={`Galería ${index + 1} de ${product.name}`} key={image} />)}</div></div>}</Layout>
}

function Admin() {
  return <Layout><section className="admin"><div className="admin-intro"><p className="kicker">ESPACIO DE GESTIÓN</p><h1>Administración</h1><p>Gestioná los alojamientos visibles en Horizonte.</p></div><div className="admin-menu"><Link to="/administracion/productos/nuevo" className="primary">+ Agregar producto</Link><Link to="/administracion/productos" className="outline dark">Lista de productos</Link></div></section><div className="admin-mobile"><span>⌁</span><h2>Panel disponible sólo en desktop</h2><p>Para gestionar el catálogo, abrí esta página en una pantalla más amplia.</p></div></Layout>
}

function ProductForm() {
  const navigate = useNavigate(); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(''); try { const form = new FormData(event.currentTarget); await productsApi.create(form); navigate('/administracion/productos') } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo guardar.') } finally { setSaving(false) } }
  return <Layout><section className="admin-page"><Link to="/administracion" className="text-link">← Administración</Link><p className="kicker">NUEVA ESTADÍA</p><h1>Agregar producto</h1><form onSubmit={submit} className="product-form"><label>Nombre<input name="name" required maxLength={120} placeholder="Ej. Casa Bruma" /></label><label>Categoría<select name="category" required defaultValue=""><option value="" disabled>Elegí una categoría</option><option>Cabañas</option><option>Casas</option><option>Hoteles</option><option>Departamentos</option><option>Estancias</option></select></label><label>Ciudad<input name="city" required placeholder="Ej. Bariloche" /></label><label>Precio por noche (ARS)<input name="price" required type="number" min="1" step="1" placeholder="120000" /></label><label className="full">Descripción<textarea name="description" required maxLength={1200} placeholder="Contá qué hace especial a esta estadía." rows={5} /></label><label className="full upload-label">Imágenes<input name="images" required type="file" accept="image/*" multiple /><span>Podés subir una o más imágenes (máx. 5 MB por archivo).</span></label>{error && <p className="form-error" role="alert">{error}</p>}<div className="form-actions"><Link to="/administracion" className="ghost dark">Cancelar</Link><button className="primary" disabled={saving}>{saving ? 'Guardando…' : 'Guardar producto'}</button></div></form></section></Layout>
}

function ProductList() {
  const [data, setData] = useState<ProductPage | null>(null); const [error, setError] = useState(''); const [page, setPage] = useState(0); const [removing, setRemoving] = useState<number | null>(null)
  const load = () => productsApi.list(page).then(setData).catch(reason => setError(reason.message)); useEffect(() => { void load() }, [page])
  async function remove(product: Product) { if (!window.confirm(`¿Eliminar “${product.name}”? Esta acción no se puede deshacer.`)) return; setRemoving(product.id); try { await productsApi.remove(product.id); if (data?.content.length === 1 && page > 0) setPage(page - 1); else load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo eliminar.') } finally { setRemoving(null) } }
  return <Layout><section className="admin-page wide"><Link to="/administracion" className="text-link">← Administración</Link><div className="table-heading"><div><p className="kicker">CATÁLOGO</p><h1>Lista de productos</h1></div><Link to="/administracion/productos/nuevo" className="primary">+ Agregar producto</Link></div>{error && <p className="form-error">{error}</p>}{data ? <><div className="table-wrap"><table><thead><tr><th>Id</th><th>Nombre</th><th>Categoría</th><th>Acciones</th></tr></thead><tbody>{data.content.map(product => <tr key={product.id}><td>#{product.id}</td><td><Link to={`/productos/${product.id}`}>{product.name}</Link></td><td>{product.category}</td><td><button className="delete" onClick={() => remove(product)} disabled={removing === product.id}>{removing === product.id ? 'Eliminando…' : 'Eliminar producto'}</button></td></tr>)}</tbody></table></div><Pagination page={data.number} total={data.totalPages} onPage={setPage} /></> : <p className="loading">Cargando catálogo…</p>}</section></Layout>
}

function Pagination({ page, total, onPage }: { page: number; total: number; onPage: (page: number) => void }) { return <div className="pagination"><button onClick={() => onPage(0)} disabled={page === 0}>« Inicio</button><button onClick={() => onPage(page - 1)} disabled={page === 0}>← Anterior</button><span>Página {page + 1} de {Math.max(total, 1)}</span><button onClick={() => onPage(page + 1)} disabled={page >= total - 1}>Siguiente →</button></div> }

export default function App() { return <Routes><Route path="/" element={<Home />} /><Route path="/productos/:id" element={<Detail />} /><Route path="/administracion" element={<Admin />} /><Route path="/administracion/productos/nuevo" element={<ProductForm />} /><Route path="/administracion/productos" element={<ProductList />} /><Route path="*" element={<Home />} /></Routes> }
